# -*- coding: utf-8 -*-
"""EDA_Analysis_Flood.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD-rwiBEJcZTJOkqTgcc0WFxZYywymFj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report, confusion_matrix

dataframe=pd.read_csv("/content/Flood.csv")

dataframe.head()

dataframe.info()

dataframe.describe()

dataframe.isnull().sum()

x = dataframe.drop(['FloodProbability', 'PopulationScore'], axis=1)

y=dataframe['FloodProbability']

x

scaler=StandardScaler()
scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=46)

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

accuracy=model.score(x_test,y_test)

accuracy

plt.scatter(y_test,y_pred)

dataframe.corr()

dataframe.hist(figsize=(20,20))