# -*- coding: utf-8 -*-
"""FuleConsumption.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD-rwiBEJcZTJOkqTgcc0WFxZYywymFj
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import LabelEncoder

dataframe=pd.read_csv("/content/FuelConsumption.csv")

dataframe

from matplotlib import pyplot as plt
dataframe['CYLINDERS'].plot(kind='line', figsize=(8, 4), title='CYLINDERS')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
dataframe['FUEL CONSUMPTION'].plot(kind='hist', bins=20, title='FUEL CONSUMPTION')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
dataframe.groupby('TRANSMISSION').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

dataframe.columns

dataframe.info()

df.describe()

df=dataframe.drop(['MODEL','MAKE','VEHICLE CLASS'],axis=1)

df

encode=LabelEncoder()
df['TRANSMISSION']=encode.fit_transform(df['TRANSMISSION'])

encode=LabelEncoder()
df['FUEL']=encode.fit_transform(df['FUEL'])

df.head()

x=df.drop(['FUEL CONSUMPTION'],axis=1)
y=df['FUEL CONSUMPTION']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

model= LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

print("accuracy score",mean_squared_error(y_test, y_pred))
print("r2 score",r2_score(y_test, y_pred))







