# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10O6fFMH04O9Gjb1cfQ8cyVmWqDweRqTD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

df=pd.read_csv("/content/Salary_dataset.csv")

df.shape

df.info()

df.columns

x=df.drop("Salary",axis=1)
y=df["Salary"]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

model=LinearRegression()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)

mse

r2=r2_score(y_test,y_pred)

r2

