# -*- coding: utf-8 -*-
"""Mental_Health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuGrzll4Pe8fMw7QF6HTVmDGPg6Q7mxS
"""

import pandas as pd

df=pd.read_csv("/content/mental_health_and_technology_usage_2024.csv")

# Analyze the dataset

df.describe()

df.info()

df.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

df.dtypes

# Label the columns present in dataset

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])
df["Mental_Health_Status"]=le.fit_transform(df["Mental_Health_Status"])
df["Stress_Level"]=le.fit_transform(df["Stress_Level"])
df["Support_Systems_Access"]=le.fit_transform(df["Support_Systems_Access"])
df["Work_Environment_Impact"]=le.fit_transform(df["Work_Environment_Impact"])
df["Online_Support_Usage"]=le.fit_transform(df["Online_Support_Usage"])
df["User_ID"]=le.fit_transform(df["User_ID"])

df.head()

df.columns

x=df[["Mental_Health_Status","Stress_Level","Support_Systems_Access","Work_Environment_Impact","Online_Support_Usage"]] # Use a list of column names enclosed in square brackets
y=["Gender"]

x.head()

y = df["Gender"] # Assign y to the "Gender" column of the DataFrame
y.head()

# split the dataset into train and test dataset

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=45)

# initiate the model

from sklearn.svm import SVR

model=SVR()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

model.score(x_test,y_test)

from sklearn.metrics import mean_squared_error,r2_score

mse=mean_squared_error(y_test,y_pred)
mse

r2=r2_score(y_test,y_pred)
r2



