# -*- coding: utf-8 -*-
"""Stock_Prize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTphuFVQlGoeKbk4R4eJOuGzm06-qHVX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df=pd.read_csv("/content/BSE SENSEX.csv")

df

df.info()

df.describe()

df.columns

x=df[['Open','High','Low']]
y=df['Close']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=45)

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print("Mean Squared Error:",mse)
print("R-squared:",r2)