# -*- coding: utf-8 -*-
"""SVM(C).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjeWcNXZ-5bYFPJS-YEoPTTdU6LP48Qz
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

df=pd.read_csv(r"C:\Users\HP\Downloads\Python Projecs\Python CSV File\Cancer_Data.csv")

df.head()

df.info()

df.describe()

df.isnull().sum()

df.abs

import numpy as np

np.corrcoef(df['radius_mean'],df['texture_mean'])

df.columns

dataframe=df[['id','diagnosis','concavity_mean','texture_worst']]

dataframe

label_encoder=LabelEncoder()

dataframe['diagnosis']=label_encoder.fit_transform(dataframe['diagnosis'])

dataframe.head()

x=dataframe.drop("diagnosis",axis=1)
y=dataframe['diagnosis']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Create an SVM(C) model
model=SVC(kernel='linear')

# train the model

model.fit(x_train,y_train)


# make prediction on the test data set
y_pred=model.predict(x_test)

# Evaluate the model

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:",accuracy)




