# -*- coding: utf-8 -*-
"""walmart Stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ht-0rNjdevX0hlz2XRSeMeVgOiRPepYm
    
dataset file is locatd at

https://www.kaggle.com/datasets/muhammadehsan000/walmart-stocks-dataset-2000-2024
"""

# import import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score

#  load dataset

df=pd.read_csv("/content/WMT.csv")

df

# Analyse the dataset

df.isnull().sum()

df.dropna()

df.info()

df.describe()

df.shape

df.columns

# split the dataset into dependent and independent variabele
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

x

y

# Building the model
model=LinearRegression()

# Apply Label Encoding to the 'Date' column in the DataFrame
df['Date'] = le.fit_transform(df['Date'])

# Redo the split after the transformation
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)

mse



